name: CI/CD Pipeline for MEAN

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    # ----------------------------------------------------------
    # Login to Docker Hub
    # ----------------------------------------------------------
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    # ----------------------------------------------------------
    # Build and Push Frontend Image
    # ----------------------------------------------------------
    - name: Build & Push Frontend Image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-project:latest ./frontend
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-project:latest

    # ----------------------------------------------------------
    # Build and Push Backend Image
    # ----------------------------------------------------------
    - name: Build & Push Backend Image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-project:latest ./backend
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-project:latest

    # ----------------------------------------------------------
    # Deploy to EC2
    # ----------------------------------------------------------
    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd sachindevgantayat-assigment

          # Pull latest code
          git pull origin main

          # Pull updated images
          docker compose pull

          # Recreate containers with latest images
          docker compose up -d

          # Clean unused images
          docker image prune -f
